export const BookJson = [
  {
    biSeq: "1",
    biName: "소나기",
    biAuthor: "오한수작가",
    biPublisher: "오한수출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "광장",
    biAuthor: "강아지",
    biPublisher: "강아지출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "완두콩",
    biAuthor: "호랑이",
    biPublisher: "호랑이출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "빨간망토",
    biAuthor: "새",
    biPublisher: "새 출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "링",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "파라노말액티비티",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "우리들의 일그러진",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "앵무새 죽이기",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
];
