export const BookJson = [
  {
    biSeq: "1",
    biName: "오한수 죽이기",
    biAuthor: "오한수작가",
    biPublisher: "오한수출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "강아지 죽이기",
    biAuthor: "강아지",
    biPublisher: "강아지출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "호랑이 죽이기",
    biAuthor: "호랑이",
    biPublisher: "호랑이출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "새 죽이기",
    biAuthor: "새",
    biPublisher: "새 출판",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "고라니 죽이기",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "고라니 죽이기",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "고라니 죽이기",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
  {
    biSeq: "1",
    biName: "고라니 죽이기",
    biAuthor: "고라니",
    biPublisher: "고라니출판1",
    biPage: "1302",
    biIsbn: "가고가",
  },
];
